import Link from "next/link";

const sections = [
  {
    heading: "How to choose the right freight mode",
    body: "Selecting between sea, air, and land freight comes down to three factors: weight, urgency, and budget. Sea freight is the most cost-effective option for large or heavy cargo — a standard 20-foot container holds roughly 25–28 tonnes of general goods and the cost per kilogram is significantly lower than air. The trade-off is time: most intercontinental sea routes take two to six weeks depending on port pairs and transshipment. Air freight compresses that to one to five days but costs five to ten times more per kilogram. Land freight sits in the middle — fast for regional moves, constrained by road crossings and border processing times. Use our rate calculator to compare estimated costs, then decide based on your delivery window and the value of your cargo.",
    link: { href: "/guides/sea-vs-air-freight", label: "Compare sea vs. air freight →" },
  },
  {
    heading: "What really causes customs delays — and how to avoid them",
    body: "Customs delays are almost always caused by paperwork problems, not physical inspections. The most common issues are vague product descriptions ('electronic goods' instead of 'USB-C laptop charger, 65W, consumer electronics'), mismatched values between invoice and actual sale price, and missing consignee contact details. Customs officers need to classify your goods, assess duties, and confirm the declared value is plausible. Providing a clear commercial invoice, an accurate HS tariff code, and complete receiver contact information at booking can cut clearance from days to hours. For regulated categories — food, cosmetics, batteries, pharmaceuticals — ask for guidance before you book, because additional permits or certificates are often required.",
    link: { href: "/guides/customs-basics-for-shippers", label: "Read the customs basics guide →" },
  },
  {
    heading: "Why dimensional weight matters for your shipping cost",
    body: "Carriers charge by whichever is greater: actual weight or dimensional weight (also called volumetric weight). Dimensional weight is calculated by multiplying length × width × height in centimetres, then dividing by a divisor — usually 5,000 for air freight and 4,000 for some road services. A lightweight but bulky package — say a 2 kg item in a 60 × 40 × 40 cm box — has a dimensional weight of 19.2 kg on air freight. You would be billed for 19.2 kg, not 2 kg. The fix is simple: use the smallest practical box for your goods. Right-sizing packaging reduces both shipping cost and the amount of void fill you need.",
    link: { href: "/guides/dimensional-weight-explained", label: "Learn how to calculate dimensional weight →" },
  },
  {
    heading: "Packing for shipping: the mistakes that cause damage claims",
    body: "The majority of transit damage comes from packaging failures, not rough handling. The three most common mistakes are using underpowered cartons (single-wall when double-wall is needed), leaving void space that lets contents shift, and sealing with a single strip of tape down the centre instead of an H-pattern on all seams. Heavy items on top of lighter ones, reused cartons that are already soft or deformed, and labels placed over seams or around corners round out the list. A good test: close and tape the box, then hold it by the bottom and shake. If you hear or feel movement, add more cushioning before it goes into the carrier's hands.",
    link: { href: "/guides/how-to-pack-for-shipping", label: "Full packing guide →" },
  },
  {
    heading: "E-commerce shipping: building a process that scales",
    body: "For online sellers, shipping is part of the product experience. Customers judge delivery speed, packaging condition, and how well you communicated updates — all separately from the item itself. A scalable shipping process has four parts: a consistent packing standard (same materials, same box sizes for your SKU range), a clear service-level agreement per order type (standard vs. express), automated tracking communication so customers get updates without emailing support, and a returns process defined before the first order ships. Getting these right before peak season — not during it — is what separates stores that grow from those that break under volume.",
    link: { href: "/guides/ecommerce-shipping-checklist", label: "E-commerce shipping checklist →" },
  },
  {
    heading: "Understanding your shipment tracking: status by status",
    body: "Tracking events are generated by scans at carrier hubs, customs checkpoints, and sorting facilities — often from different systems that don't always speak the same language. 'In transit' can mean the cargo is on a vessel, in a warehouse, or sitting in a truck. The status that actually requires your attention is 'held by customs' — this means action is needed, usually a document or a duty payment. 'Delivery exception' also deserves a prompt follow-up, especially if there's no update within 48 hours. Everything else, including long gaps on sea freight, is usually normal. Knowing the difference saves you hours of unnecessary anxiety and lets you focus energy on the situations that genuinely need it.",
    link: { href: "/guides/tracking-status-explained", label: "Tracking status guide →" },
  },
];

export default function EditorialContent() {
  return (
    <section className="bg-background px-4 py-14 sm:px-6 sm:py-20">
      <div className="mx-auto max-w-4xl">
        <p className="text-xs font-bold uppercase tracking-widest text-gold">Shipping knowledge</p>
        <h2 className="mt-3 text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
          Practical guides for every freight decision
        </h2>
        <p className="mt-4 text-base leading-relaxed text-muted">
          Whether you are booking your first international shipment or managing a regular freight
          schedule, these answers cover the decisions that matter most.
        </p>

        <div className="mt-12 space-y-12">
          {sections.map((s) => (
            <article key={s.heading}>
              <h3 className="text-lg font-semibold text-foreground sm:text-xl">{s.heading}</h3>
              <p className="mt-3 text-base leading-relaxed text-muted">{s.body}</p>
              <Link
                href={s.link.href}
                className="mt-3 inline-block text-sm font-semibold text-gold hover:underline"
              >
                {s.link.label}
              </Link>
            </article>
          ))}
        </div>

        <p className="mt-12 text-sm text-muted">
          Browse all topics in the{" "}
          <Link href="/guides" className="font-semibold text-gold hover:underline">
            guides library
          </Link>
          {" "}or start with the{" "}
          <Link href="/shipping-guide" className="font-semibold text-gold hover:underline">
            shipping guide overview
          </Link>
          .
        </p>
      </div>
    </section>
  );
}
